### ISSUE TITLE
npm run start-solid-server fails

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/solid-stream-aggregator-demo#1]
I did the following steps:

1. Clone repo.
2. `npm run start-solid-server`

I get the following error:

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/community-solid-server - Not found
npm ERR! 404 
npm ERR! 404  'community-solid-server@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pheyvaer/.npm/_logs/2023-04-26T13_09_17_402Z-debug-0.log
```

When I do `npm i` first (which is not in the instructions) and then do `npm run start-solid-server` again I get:

```shell
> ssa-demo@1.0.0 start-solid-server
> cd scripts && rm -rf data/.internal/ && npx community-solid-server --config ./pod/config/unsafe.json -f ./data/ --seededPodConfigJson ./pod/multiSolidPod.json

oidc-provider WARNING: Unsupported Node.js runtime version. Use ^12.19.0, ^14.15.0, or ^16.13.0
2023-04-26T14:00:30.179Z [Components.js] info: Initiating component discovery from /Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@solid/community-server/
node ./bin/server.js [args]

Options:
      --version         Show version number                            [boolean]
  -c, --config
  [array] [default: ["/Users/pheyvaer/Development/solidlab/ssa-demo/node_modules
                                 /@solid/community-server/config/default.json"]]
  -l, --loggingLevel
        [string] [choices: "error", "warn", "info", "verbose", "debug", "silly"]
                                                               [default: "info"]
  -m, --mainModulePath                                                  [string]

Could not build the config files from /Users/pheyvaer/Development/solidlab/ssa-demo/scripts/pod/config/unsafe.json
Cause: Error while parsing import path 'https://linkedsoftwaredependencies.org/bundles/npm/@treecg/versionawareldesinldp/^0.0.0/config/' in /Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@treecg/versionawareldesinldp: /Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@treecg/versionawareldesinldp/config/ does not exist.
Error: Error while parsing import path 'https://linkedsoftwaredependencies.org/bundles/npm/@treecg/versionawareldesinldp/^0.0.0/config/' in /Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@treecg/versionawareldesinldp: /Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@treecg/versionawareldesinldp/config/ does not exist.
    at /Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/componentsjs/lib/loading/ModuleStateBuilder.js:289:35
    at async Promise.all (index 321)
    at async ModuleStateBuilder.buildComponentImportPaths (/Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/componentsjs/lib/loading/ModuleStateBuilder.js:274:9)
    at async ModuleStateBuilder.buildModuleState (/Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/componentsjs/lib/loading/ModuleStateBuilder.js:30:29)
    at async ComponentsManagerBuilder.build (/Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/componentsjs/lib/loading/ComponentsManagerBuilder.js:63:27)
    at async AppRunner.createComponentsManager (/Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@solid/community-server/dist/init/AppRunner.js:151:35)
    at async AppRunner.createCli (/Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@solid/community-server/dist/init/AppRunner.js:135:33)
    at async AppRunner.runCli (/Users/pheyvaer/Development/solidlab/ssa-demo/node_modules/@solid/community-server/dist/init/AppRunner.js:100:21)
````

**Comment by argahsuknesib** [comment]
Hi pieter, thanks for the issue.

The commit [0c276b9](https://github.com/argahsuknesib/ssa-demo/commit/0c276b9607bf2e00ccf6f671b67f38b68d8a51de) should solve this.

Apparently there is an issue with the VersionAwareLDESinLDP library that it works *ONLY* with the global installations of the CSS and not the local with the package.json.
Therefore, I removed it from the package.json and updated the README.

**Comment by pheyvaer** [comment]
Thanks! I will give it a try. Is this issue with the CSS already documented somewhere?

**Comment by argahsuknesib** [comment]
I don't think so. I have not documented this. Maybe @woutslabbinck has an idea as he faced this issue too.
